name: CI/CD Pipeline

on:
  push:
    branches:
      - main
#  pull_request:
#    branches:
#      - main

  workflow_dispatch:

jobs:
  prepare:
    name: Vorbereitung
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Node.js Setup
        uses: actions/checkout@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Abhängigkeiten installieren
        run: npm ci

      - name: Cache node_modules
        uses: actions/cache@v4
        id: node-modules-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}

  lint:
    name: Linting
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Node.js Setup
        uses: actions/checkout@v4
        with:
          node-version: '18'
          cache: 'npm'

      # Restore cached node_modules
      - name: Restore node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Linting-Prüfung
        run: npm run lint

  format:
    name: Format-Check
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Node.js Setup
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      # Restore cached node_modules
      - name: Restore node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Format-Prüfung
        run: npm run format:check

  build:
    name: Build
    needs: [ lint, format ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Node.js Setup
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      # Restore cached node_modules
      - name: Restore node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Prisma generieren
        run: npx prisma generate

      - name: Build der Anwendung
        run: npm run build

      # Cache build output
      - name: Cache build output
        uses: actions/cache@v4
        with:
          path: dist
          key: ${{ runner.os }}-build-${{ github.sha }}

  test:
    name: Integration Tests
    needs: build
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          DB_PORT: 5432
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: test
          POSTGRES_DB: budget_db
        ports:
          - $DB_PORT:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:6
        env:
          REDIS_PORT: 6379
        ports:
          - $REDIS_PORT
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Node.js Setup
        uses: actions/checkout@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Restore node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Restore build output
        uses: actions/checkout@v4
        with:
          path: dist
          key: $${{ runner.os }}-build-${{ github.sha }}

      - name: Generate Prisma
        run: npx prisma generate

      - name: Run prisma migrations
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: "postgresql://admin:test@localhost:5432/budget_db?schema=public"

      - name: Run integration tests
        run: npm test
        env:
          PORT: 3000
          HOST: localhost
          NODE_ENV: production
          DB_PORT: 5432
          DB_NAME: budget_db
          DB_USER: admin
          DB_PASSWORD: test
          DB_HOST: localhost
          DB_POSTGRES: budget_db
          DATABASE_URL: "postgresql://admin:test@localhost:5432/budget_db?schema=public"
          REDIS_HOST: localhost
          REDIS_PORT: 6379
          JWT_SECRET: secret
          JWT_EXPIRE_IN: 5min
          JWT_REFRESH_TOKEN_TTL: 24h
          JWT_ACCESS_TOKEN_TTL: 3600
          JWT_TOKEN_ISSUER: localhost
          JWT_TOKEN_AUDIENCE: localhost
          RATE_LIMIT_MAX: 1000
          COOKIE_SECRET: cookieSecret
          COOKIE_NAME: cookie
          COOKIE_SECURED: false
